spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: 'jdbc:postgresql://localhost:5432/postgres?currentSchema=DHBW42'
        username: postgres
        password: 1234

    jpa:
        open-in-view: false

        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                hbm2ddl:
                    auto: update
                show_sql: false

server:
    port: 8000

    servlet:
        context-path: /v1

springdoc:
    api-docs:
        enabled: false

    swagger-ui:
        url: /openapi.yml
        path: /swagger
